### ISSUE TITLE
BOM item "Electric Motor with gear reduction" link does not work.

### ISSUE THREAD

**Issue by erimsa** [mwood77/osww#8]
BOM item "Electric Motor with gear reduction" link is removed from Aliexpress. 

![image](https://github.com/user-attachments/assets/8abcf480-ae96-4073-8d65-d22b687ebe2c)

**Comment by mwood77** [comment]
BOM updated: https://github.com/mwood77/osww/commit/890974d3d81d2fde0b7f9a80a5ce03aaf5c2bfa3

**Comment by erimsa** [comment]
Thanks.
